In [1]:
import numpy as np
from Assignment_problem_auction_algorithm import auction_algorithm, swap, auction, isHappy

In [2]:
# determine the doctor number and patient number
doctor_number = 12
patient_number = 12

In [3]:
# The capacity of each doctor and the preference of each patient are randomly generated here
capacity = np.zeros([doctor_number,1]);
while True:
    for j in range(doctor_number):
        capacity[j] = np.random.randint(np.rint(patient_number*2/doctor_number + 1))+1
    legal_capacity = np.sum(capacity)
    if legal_capacity > patient_number:
        break
rating = np.zeros([patient_number,doctor_number])
for i in range(patient_number):
    rating[i, :] = np.random.permutation(doctor_number)
#Patient_ratings = array2table(rating,'VariableNames',('Doctor'+string(1:doctor_number)));
#display(Patient_ratings)

In [4]:
output = auction_algorithm(rating, capacity)

In [5]:
print(rating)

[[11.  6.  4. 10.  7.  3.  5.  1.  8.  9.  0.  2.]
 [ 5. 10.  2.  4.  6. 11.  8.  9.  3.  1.  7.  0.]
 [ 1. 11.  3.  6.  0.  2.  4.  8.  7. 10.  5.  9.]
 [ 0.  3.  5.  1.  9.  7.  6.  8. 10.  4.  2. 11.]
 [ 3.  7. 10.  0.  9.  8.  2.  6.  5.  4. 11.  1.]
 [11.  5.  6.  2.  8. 10.  4.  1.  9.  7.  0.  3.]
 [ 5.  4.  6.  8.  0.  1.  2.  7.  3. 11.  9. 10.]
 [ 9.  3.  4.  6.  8.  2. 11.  0. 10.  7.  5.  1.]
 [ 6.  8. 10.  3.  7.  0.  4.  1.  5.  2. 11.  9.]
 [ 3.  2.  4.  8.  0. 10.  5. 11.  1.  6.  7.  9.]
 [ 1.  3.  6.  9. 10.  8.  5.  7.  4. 11.  0.  2.]
 [ 7. 10.  8.  1.  2.  3.  9.  0.  6. 11.  5.  4.]]


In [6]:
print(capacity)

[[1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [1.]
 [2.]
 [3.]
 [1.]
 [3.]
 [3.]
 [3.]]


In [7]:
# The assigned doctor for each patient
print(output)

[[ 3.]
 [ 5.]
 [ 1.]
 [11.]
 [10.]
 [ 0.]
 [ 9.]
 [ 6.]
 [10.]
 [ 7.]
 [ 9.]
 [ 9.]]


In [8]:
# The preference score of the assigned plan
for i in range(patient_number):
    print(rating[i,int(output[i])])

10.0
11.0
11.0
11.0
11.0
11.0
11.0
11.0
11.0
11.0
11.0
11.0
